// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwxkwIbexMPMkdCQXU4WN6zpLEDGpaxA',
    appId: '1:1001205486815:web:52e957cfb2ce17f592c56a',
    messagingSenderId: '1001205486815',
    projectId: 'whatsapp-clone-5ec02',
    authDomain: 'whatsapp-clone-5ec02.firebaseapp.com',
    storageBucket: 'whatsapp-clone-5ec02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60vvViSIqYwp5jrg2VHOgSeXaccE5qeY',
    appId: '1:1001205486815:android:cc4291995a35fe4292c56a',
    messagingSenderId: '1001205486815',
    projectId: 'whatsapp-clone-5ec02',
    storageBucket: 'whatsapp-clone-5ec02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt77mDTgrB9ZUbvWq0bTqu1qylUn8Zl-E',
    appId: '1:1001205486815:ios:c73c331cc91ab10592c56a',
    messagingSenderId: '1001205486815',
    projectId: 'whatsapp-clone-5ec02',
    storageBucket: 'whatsapp-clone-5ec02.appspot.com',
    iosClientId: '1001205486815-aee9eiii64emu02sv9gklf8euqakgl8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt77mDTgrB9ZUbvWq0bTqu1qylUn8Zl-E',
    appId: '1:1001205486815:ios:c73c331cc91ab10592c56a',
    messagingSenderId: '1001205486815',
    projectId: 'whatsapp-clone-5ec02',
    storageBucket: 'whatsapp-clone-5ec02.appspot.com',
    iosClientId: '1001205486815-aee9eiii64emu02sv9gklf8euqakgl8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );
}
