// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WL5d9tbhlMRJGPLOvovTImUxekzvdS4',
    appId: '1:516108277974:web:32531e4a4b7d6f88a95177',
    messagingSenderId: '516108277974',
    projectId: 'whatsapp-flutter-b3b13',
    authDomain: 'whatsapp-flutter-b3b13.firebaseapp.com',
    storageBucket: 'whatsapp-flutter-b3b13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-31YVdM-DFUg6kWIc-Qi1MKE3whjsik',
    appId: '1:516108277974:android:f2f8482059dc8ceaa95177',
    messagingSenderId: '516108277974',
    projectId: 'whatsapp-flutter-b3b13',
    storageBucket: 'whatsapp-flutter-b3b13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt90jM-X3NCSeOyW6bJcRmgWd-jfuuBRI',
    appId: '1:516108277974:ios:c792ff574fa76487a95177',
    messagingSenderId: '516108277974',
    projectId: 'whatsapp-flutter-b3b13',
    storageBucket: 'whatsapp-flutter-b3b13.appspot.com',
    androidClientId: '516108277974-082c9uqooed7b0fmtvakk53hdstnmb0k.apps.googleusercontent.com',
    iosClientId: '516108277974-ecod2r48mpjf2m8nle6hn6m1nstt6er2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt90jM-X3NCSeOyW6bJcRmgWd-jfuuBRI',
    appId: '1:516108277974:ios:c792ff574fa76487a95177',
    messagingSenderId: '516108277974',
    projectId: 'whatsapp-flutter-b3b13',
    storageBucket: 'whatsapp-flutter-b3b13.appspot.com',
    androidClientId: '516108277974-082c9uqooed7b0fmtvakk53hdstnmb0k.apps.googleusercontent.com',
    iosClientId: '516108277974-ecod2r48mpjf2m8nle6hn6m1nstt6er2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );
}
